import {
  SiSteam,
  SiPlaystation,
  SiXbox,
  SiAppstore,
  SiGogdotcom,
  SiNintendo,
  SiGoogleplay,
  SiEpicgames,
  SiItchdotio,
} from 'react-icons/si'

export const Storefronts = [
  {
    id: 1,
    name: 'Steam',
    domain: 'store.steampowered.com',
    slug: 'steam',
    games_count: 62750,
    icon: <SiSteam />,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 17306,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 16016,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 15117,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 13149,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 13011,
      },
    ],
  },
  {
    id: 3,
    name: 'PlayStation Store',
    domain: 'store.playstation.com',
    slug: 'playstation-store',
    icon: <SiPlaystation />,
    games_count: 7745,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 17306,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 16016,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 15117,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 13149,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 13011,
      },
    ],
  },
  {
    id: 2,
    name: 'Xbox Store',
    domain: 'microsoft.com',
    slug: 'xbox-store',
    games_count: 4712,
    icon: <SiXbox />,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 17306,
      },
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 16016,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 15117,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 12604,
      },
      {
        id: 3439,
        slug: 'life-is-strange-episode-1-2',
        name: 'Life is Strange',
        added: 12542,
      },
      {
        id: 802,
        slug: 'borderlands-2',
        name: 'Borderlands 2',
        added: 12531,
      },
    ],
  },
  {
    id: 4,
    name: 'App Store',
    domain: 'apps.apple.com',
    slug: 'apple-appstore',
    games_count: 72461,
    icon: <SiAppstore />,
    games: [
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 12604,
      },
      {
        id: 3439,
        slug: 'life-is-strange-episode-1-2',
        name: 'Life is Strange',
        added: 12542,
      },
      {
        id: 802,
        slug: 'borderlands-2',
        name: 'Borderlands 2',
        added: 12531,
      },
      {
        id: 4286,
        slug: 'bioshock',
        name: 'BioShock',
        added: 11502,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 11274,
      },
    ],
  },
  {
    id: 5,
    name: 'GOG',
    domain: 'gog.com',
    slug: 'gog',
    games_count: 4148,
    icon: <SiGogdotcom />,
    games: [
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 16016,
      },
      {
        id: 3439,
        slug: 'life-is-strange-episode-1-2',
        name: 'Life is Strange',
        added: 12542,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 11274,
      },
      {
        id: 422,
        slug: 'terraria',
        name: 'Terraria',
        added: 9609,
      },
      {
        id: 23027,
        slug: 'the-walking-dead',
        name: 'The Walking Dead: Season 1',
        added: 9458,
      },
      {
        id: 3287,
        slug: 'batman-arkham-knight',
        name: 'Batman: Arkham Knight',
        added: 9216,
      },
    ],
  },
  {
    id: 6,
    name: 'Nintendo Store',
    domain: 'nintendo.com',
    slug: 'nintendo',
    games_count: 8825,
    icon: <SiNintendo />,
    games: [
      {
        id: 3328,
        slug: 'the-witcher-3-wild-hunt',
        name: 'The Witcher 3: Wild Hunt',
        added: 16016,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 13149,
      },
      {
        id: 4062,
        slug: 'bioshock-infinite',
        name: 'BioShock Infinite',
        added: 12604,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 11274,
      },
      {
        id: 2454,
        slug: 'doom',
        name: 'DOOM (2016)',
        added: 10905,
      },
      {
        id: 3939,
        slug: 'payday-2',
        name: 'PAYDAY 2',
        added: 10465,
      },
    ],
  },
  {
    id: 7,
    name: 'Xbox 360 Store',
    domain: 'marketplace.xbox.com',
    slug: 'xbox360',
    icon: <SiXbox />,
    games_count: 1917,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 17306,
      },
      {
        id: 4200,
        slug: 'portal-2',
        name: 'Portal 2',
        added: 15117,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 5679,
        slug: 'the-elder-scrolls-v-skyrim',
        name: 'The Elder Scrolls V: Skyrim',
        added: 13149,
      },
      {
        id: 4291,
        slug: 'counter-strike-global-offensive',
        name: 'Counter-Strike: Global Offensive',
        added: 13011,
      },
      {
        id: 12020,
        slug: 'left-4-dead-2',
        name: 'Left 4 Dead 2',
        added: 12897,
      },
    ],
  },
  {
    id: 8,
    name: 'Google Play',
    domain: 'play.google.com',
    slug: 'google-play',
    icon: <SiGoogleplay />,
    games_count: 16824,
    games: [
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 13536,
        slug: 'portal',
        name: 'Portal',
        added: 12792,
      },
      {
        id: 3439,
        slug: 'life-is-strange-episode-1-2',
        name: 'Life is Strange',
        added: 12542,
      },
      {
        id: 802,
        slug: 'borderlands-2',
        name: 'Borderlands 2',
        added: 12531,
      },
      {
        id: 13537,
        slug: 'half-life-2',
        name: 'Half-Life 2',
        added: 11571,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 11274,
      },
    ],
  },
  {
    id: 9,
    name: 'itch.io',
    domain: 'itch.io',
    slug: 'itch',
    icon: <SiItchdotio />,
    games_count: 551010,
    games: [
      {
        id: 613,
        slug: 'bastion',
        name: 'Bastion',
        added: 7232,
      },
      {
        id: 5525,
        slug: 'brutal-legend',
        name: 'Brutal Legend',
        added: 6966,
      },
      {
        id: 1010,
        slug: 'transistor',
        name: 'Transistor',
        added: 6555,
      },
      {
        id: 3740,
        slug: 'fez',
        name: 'FEZ',
        added: 5980,
      },
      {
        id: 1774,
        slug: 'grim-fandango-remastered',
        name: 'Grim Fandango Remastered',
        added: 5356,
      },
      {
        id: 356714,
        slug: 'among-us',
        name: 'Among Us',
        added: 5047,
      },
    ],
  },
  {
    id: 11,
    name: 'Epic Games',
    domain: 'epicgames.com',
    slug: 'epic-games',
    icon: <SiEpicgames />,
    games_count: 916,
    games: [
      {
        id: 3498,
        slug: 'grand-theft-auto-v',
        name: 'Grand Theft Auto V',
        added: 17306,
      },
      {
        id: 5286,
        slug: 'tomb-raider',
        name: 'Tomb Raider (2013)',
        added: 13564,
      },
      {
        id: 28,
        slug: 'red-dead-redemption-2',
        name: 'Red Dead Redemption 2',
        added: 12006,
      },
      {
        id: 1030,
        slug: 'limbo',
        name: 'Limbo',
        added: 11274,
      },
      {
        id: 58175,
        slug: 'god-of-war-2',
        name: 'God of War',
        added: 10435,
      },
      {
        id: 278,
        slug: 'horizon-zero-dawn',
        name: 'Horizon Zero Dawn',
        added: 10217,
      },
    ],
  },
]
